PDM_DESPTIME = CreateConVar("pdm_despawntime", 60, 0, "Number of seconds spawned props take to despawn", 1)
PDM_KILLGOAL = CreateConVar("pdm_killgoal", 30, 0, "Number of kills needed to end the round", 1)
PDM_MAXPROPS = CreateConVar("pdm_maxprops", 100, 0, "Number of props the heli can spawn before they begin to be removed", 1)
PDM_TIMEBEFOREROUND = CreateConVar("pdm_timebeforeround", 10, 0, "Number of seconds before a round starts", 0)
PDM_TIMEAFTERROUND = CreateConVar("pdm_timeafterround", 5, 0, "Number of seconds after a round ends before the timer starts for the next one", 0)